import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TopBar, Navbar, Footer } from "@/widgets";
import { navItemsMock } from "@/widgets/navbar";
import { mockTopBarData } from "@/widgets/top-bar";
import { footerMock } from "@/widgets/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopBar {...mockTopBarData} />
        <Navbar 
          churchName="Parroquia San Juan María Vianney"
          items={navItemsMock}
        />
        <main>{children}</main>
        <Footer {...footerMock} />
      </body>
    </html>
  );
}
