/**
 * Daily Readings Book widget type definitions.
 * 
 * View models for the book-style UI that displays liturgical readings
 * with page-flipping animation.
 * 
 * @module widgets/daily-readings-book/model/types
 */

import type { Reading, ReadingType, LiturgicalColor, LiturgicalSeason } from '@/entities/liturgy';

// ============================================================================
// Reading Collections
// ============================================================================

/**
 * Represents all readings for a single liturgical day.
 * Combines metadata (date, season, color) with the actual reading texts.
 */
export interface DayReading {
  /** ISO date string (YYYY-MM-DD) */
  date: string;
  
  /** Name of the liturgical day (e.g., "2do Domingo de Adviento") */
  liturgicalDayName: string;
  
  /** Current liturgical season */
  season: LiturgicalSeason;
  
  /** Liturgical color for styling */
  liturgicalColor: LiturgicalColor;
  
  /** Array of readings for this day (First Reading, Psalm, Second Reading, Gospel) */
  readings: Reading[];
}

// ============================================================================
// Book Pagination Types
// ============================================================================

/**
 * Represents a single page in the book view.
 * Created dynamically based on container dimensions and text content.
 */
export interface BookPage {
  /** Text content for this page */
  content: string;
  
  /** Page number (1-indexed for display) */
  pageNumber: number;
  
  /** Whether this is the first page of a reading (shows header) */
  isFirstOfReading: boolean;
  
  /** Type of reading this page belongs to */
  readingType: ReadingType;
  
  /** Biblical reference for this reading */
  reference: string;
  
  /** Reading type label (e.g., "Primera Lectura", "Salmo") */
  readingTypeLabel: string;
}

/**
 * Configuration for text pagination in the book view.
 * Used by @chenglou/pretext to calculate page breaks.
 */
export interface PaginationConfig {
  /** Container width in pixels */
  containerWidth: number;
  
  /** Container height in pixels */
  containerHeight: number;
  
  /** Font size in pixels (default: 18px for accessibility) */
  fontSize: number;
  
  /** Line height multiplier (default: 1.8 for readability) */
  lineHeight: number;
  
  /** Font family string (CSS font-family value) */
  fontFamily: string;
  
  /** Horizontal padding in pixels */
  paddingX: number;
  
  /** Vertical padding in pixels */
  paddingY: number;
}

// ============================================================================
// Component Props
// ============================================================================

/**
 * Props for the DailyReadingsBook widget.
 */
export interface DailyReadingsBookProps {
  /** First day used as initial render source (RSC-friendly bootstrap prop) */
  initialDayReading?: DayReading;
  
  /** Optional: Override the pagination config */
  paginationConfig?: Partial<PaginationConfig>;
}

/**
 * Props for the liturgical flipbook wrapper.
 */
export interface LiturgicalBookProps {
  /** Flat page list generated by the paginator */
  pages: BookPage[];

  /** Responsive mode: true for one page, false for spread */
  isSinglePage: boolean;
}

// ============================================================================
// UI State Types
// ============================================================================

/**
 * Internal state for the book component.
 */
export interface BookState {
  /** Current page index (0-indexed) */
  currentPage: number;
  
  /** Total number of pages in current day's readings */
  totalPages: number;
  
  /** Whether the book is animating a page flip */
  isFlipping: boolean;
  
  /** Current reading type being viewed */
  currentReadingType: ReadingType;
}

/**
 * Reading type metadata for display labels.
 */
export const READING_TYPE_LABELS: Record<ReadingType, string> = {
  first_reading: 'Primera Lectura',
  psalm: 'Salmo Responsorial',
  second_reading: 'Segunda Lectura',
  gospel: 'Evangelio',
} as const;

/**
 * Reading type display order.
 */
export const READING_TYPE_ORDER: ReadingType[] = [
  'first_reading',
  'psalm',
  'second_reading',
  'gospel',
];
